---
- name: create loopback
  hosts: sandbox
  gather_facts: False
  connection: local
  become: yes
  become_method: enable

  tasks:
    - name: create loopback 
      ios_interface:
        name: Loopback123321
        enabled: True
        description: loopback 123321 created with ansible
    - name: assign ip to loopback
      ios_l3_interface:
        name: Loopback123321
        ipv4: 10.12.33.1/32